apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backendpod
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backendpod
          image: toregard/backend:3.0
