kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: reactiverjdbcbackend
  namespace: dev
  labels:
    app: reactiverjdbcbackend
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: reactiverjdbcbackend
  template:
    metadata:
      labels:
        deployment: reactiverjdbcbackend
    spec:
      containers:
        - name: reactiverjdbcbackend
          image: >-
            image-registry.openshift-image-registry.svc:5000/dev/reactiverjdbcbackend@sha256:68316ed405d0b5574f578b29013fbe7573de355985f4ea17f437cbd1c97b7810
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 7
  replicas: 2
  updatedReplicas: 2
  readyReplicas: 2
  availableReplicas: 2
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-12-23T12:26:53Z'
      lastTransitionTime: '2020-12-23T12:24:16Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "reactiverjdbcbackend-5fdc988556" has successfully
        progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-12-23T14:01:37Z'
      lastTransitionTime: '2020-12-23T14:01:37Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
