# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI with Maven
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    needs: compile
    name: Build Maven project
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and test project
        run: mvn -f pom.xml package
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: target/reactiverjdbcbackend-0.0.1-SNAPSHOT.jar
  deploy:
    runs-on: ubuntu-latest
    #needs: build
    name: Build Docker container and deploy to Kubernetes
    steps:
      - uses: actions/checkout@v1
      - name: Download Maven build artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact
      - name: Build Docker container
        run: |
          mkdir -p target
          mv artifact target/app.jar
          docker build -t backend/app app
      - name: Access secrets
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
        run: echo "Content of secret - $SUPER_SECRET"
      - name: Push Docker images
        run: echo "Pushing Docker image to Container Registry (e.g. ECR)"
      - name: Deploy application
        run: echo "Deploying application (e.g. Kubernetes)"

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#    - name: Build with Maven
#      run: mvn -B package --file pom.xml
#    - name: Docker Build then Push
#    - uses: tegarimansyah/docker_build_push@0.1.0
